allowCheckoutWithoutPayment: false
allowEmptyCartOnCheckout: false
allowPartialPaymentOnCheckout: false
autoSetCartShippingMethodOption: false
autoSetNewCartAddresses: false
autoSetPaymentSource: false
currency: USD
freeOrderPaymentStrategy: complete
handle: primary
minimumTotalPriceStrategy: default
name: Primary
orderReferenceFormat: '{{number[:7]}}'
primary: true
requireBillingAddressAtCheckout: false
requireShippingAddressAtCheckout: false
requireShippingMethodSelectionAtCheckout: false
sortOrder: 99
useBillingAddressForTax: false
validateOrganizationTaxIdAsVatId: false
